name: mapper_issue
description: "Testing dart_mappable with retrofit and Chopper"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  chopper: ^7.1.1
  dart_mappable: ^4.2.0
  dio: ^5.4.1
  json_annotation: ^4.8.1
  http: ^1.2.1
  retrofit: ^4.1.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.8
  build_verify: ^3.1.0
  chopper_generator: ^7.1.1
  dart_mappable_builder: ^4.2.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true

